language: scala
sudo: required
cache: packages

scala:
  - 2.11.11

env:
  global:
    - SPARK_VERSION="2.4.0"
    - HADOOP_VERSION="2.7"
    - SPARK_PATH="spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}"
    - SPARK_HOME="/tmp/${SPARK_PATH}"    
    - JAVA_VERSION=oraclejdk8
    - PATH="${PATH}:${SPARK_HOME}/bin"

before_install:
  - bash ./setup_spark.sh

script:
  - spark-submit -h
