language: scala

sudo: required
cache: packages

scala:
  - 2.11.11

env:
  global:
    - SPARK="2.4.0"
    - HADOOP="2.7"
    - SPARK_HOME="/tmp/spark-${SPARK}-bin-hadoop${HADOOP}"
    - spark-submit="${SPARK_HOME}/bin/spark-submit"

before_install:
  - ./setup_spark.sh

script:
  - ${spark-submit} -h
